# Generated by Django 4.1.7 on 2023-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_image_event_event_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_unique',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
